- src/Database/Esqueleto.hs
Follow-up to https://github.com/prowdsponsor/esqueleto/pull/152
> Correct persistent module name for example imports

- src/Database/Esqueleto/Internal/Language.hs
Follow-up on https://github.com/prowdsponsor/esqueleto/pull/154
> Use correct `in_` quoting in haddock code block

- .travis.yml
- esqueleto.cabal
- src/Database/Esqueleto/Internal/Language.hs
- src/Database/Esqueleto/Internal/PersistentImport.hs
- src/Database/Esqueleto/Internal/Sql.hs
- stack-8.0.yaml
- test/Test.hs
> Allow persistent 2.6 and base 4.9

- .travis.yml
- src/Database/Esqueleto/PostgreSQL.hs
- test/Test.hs
I've added back some missing imports that were preventing the postgres tests from building.
I've also updated the `travis.yml` to configure a local postgres install & run the tests against postgres.
> Fix postgres tests

- .editorconfig
- Makefile
- src/Database/Esqueleto/Internal/Sql.hs
- stack-8.0.yaml
- stack.yaml
- test/Test.hs
> Fixing composite key support for group by

- src/Database/Esqueleto/Internal/Sql.hs
> Cleaning up Esqueleto errors

- esqueleto.cabal
- src/Database/Esqueleto/PostgreSQL.hs
- test/Test.hs
A small variant of `array_agg` that removes duplicate values from a list.
> Add arrayAggDistinct wrapper for PostgreSQL function

- .travis.yml
- src/Database/Esqueleto/PostgreSQL.hs
- test/Test.hs
Add support for `array_remove` function.
https://www.postgresql.org/docs/10/static/functions-array.html
> Add arrayRemove wrapper for PostgreSQL function

- README.md
- src/Database/Esqueleto.hs
I'm pretty new to SQL, but I think this should be fixed.
> Fix SQL syntax in join example

- src/Database/Esqueleto/Internal/Sql.hs
This is a lightly edited git cherry-pick from https://github.com/prowdsponsor/esqueleto/pull/140 implementing SQL side casting.
> Add unsafeSqlCastAs

- changelog.md
- esqueleto.cabal
- package.yaml
This PR adds the Changelog and README to the package so that {h,st}ackage can display them.
> Add changelog and README to package

- changelog.md
- esqueleto.cabal
- package.yaml
- src/Database/Esqueleto/Internal/PersistentImport.hs
> Remove QQ re-exports

- README.md
No logic changes, only README instructions.
> Update README with Postgres info

- changelog.md
- esqueleto.cabal
- src/Database/Esqueleto.hs
- src/Database/Esqueleto/Internal/Internal.hs
- src/Database/Esqueleto/Internal/Language.hs
- test/Common/Test.hs
Fixes #151 
This PR adds a deprecation notice and suggests a migration path away.
> sub_select fix #2

- README.md
Add documentation on how to use the unsafe functions and some of the pitfalls when using them.
> Add unsafe documentation

- esqueleto.cabal
> Remove duplicated dependency

- changelog.md
- esqueleto.cabal
- src/Database/Esqueleto.hs
- src/Database/Esqueleto/Internal/Internal.hs
- test/Common/Test.hs
> Group by documentation

- test/Common/Test.hs
- test/PostgreSQL/Test.hs
> 27 date trunc postgres

- README.md
It looks like #156 fixed the issue that this part of the README is still referring to
> Remove outdated note about ON clause ordering

- src/Database/Esqueleto/Internal/Internal.hs
> Remove whitespaces from Database.Esqueleto.Internal.Internal

- changelog.md
- esqueleto.cabal
- src/Database/Esqueleto/Internal/Internal.hs
> Document isNothing

- .travis.yml
- stack-nightly.yaml
> update nightly resolver

- changelog.md
- esqueleto.cabal
- src/Database/Esqueleto/Internal/Internal.hs
> Add recommended hlint rules for proper isNothing usage

- .github/workflows/haskell.yml
- test/MySQL/Test.hs
> Github Actions

- esqueleto.cabal
> Allow attoparsec 0.14

- README.md
I don't think any of the checkboxes does apply since it's only the README :smile: but if not, let me know to update them properly
> Update status badge with GH actions and delete some whitespaces from README

- changelog.md
- esqueleto.cabal
- src/Database/Esqueleto/Experimental/From/Join.hs
> Add `SqlSelect` instance for `:&`

- src/Database/Esqueleto/Internal/Internal.hs
> Better documentation on associateJoin

- test/Common/Test.hs
> esqueleto-3.5.3.0

- .github/workflows/haskell.yml
- changelog.md
> GHC 9.2 support

- changelog.md
- esqueleto.cabal
- stack-nightly.yaml
- stack-nightly.yaml.lock
> Support `time` >= 10

- changelog.md
- esqueleto.cabal
- src/Database/Esqueleto/Internal/PersistentImport.hs
- stack-8.10.yaml
- test/Common/Test.hs
> Support persistent-2.14

- esqueleto.cabal
> Support text-2

- changelog.md
- esqueleto.cabal
- src/Database/Esqueleto/Record.hs
> Fix Haddock markup to render correctly

- changelog.md
- src/Database/Esqueleto/Experimental/From/Join.hs
> Add GetFirstTable

- examples/esqueleto-examples.cabal
- src/Database/Esqueleto/Experimental.hs
- src/Database/Esqueleto/Experimental/From/Join.hs
- test/Common/Test.hs
> write a test, do a doc

- changelog.md
> changelog.md: Add link to PR #350

- .github/workflows/haskell.yml
- changelog.md
- esqueleto.cabal
- src/Database/Esqueleto/Internal/Internal.hs
- test/Common/Test.hs
> Newlines between query chunks

- README.md
> README.md: Fix missing words

- esqueleto.cabal
> Version bump for text

- changelog.md
- esqueleto.cabal
- src/Database/Esqueleto/Internal/Internal.hs
> Derive Traversable for Value

- changelog.md
- esqueleto.cabal
- src/Database/Esqueleto/Experimental.hs
> Export SqlSelect from Database.Esqueleto.Experimental

- changelog.md
- src/Database/Esqueleto/Internal/Internal.hs
> Add fixity on question-dot operator
