esqueleto.cabal

Given that CI only seems to test against GHC 7.10 & GHC 8.0 it's safe to say that only
`base >= 4.8` is officially supported. And empirically, GHC 7.8.4 runs into the compile error below
```
Configuring component lib from esqueleto-2.5.0...
Preprocessing library esqueleto-2.5.0...
[1 of 5] Compiling Database.Esqueleto.Internal.PersistentImport ( src/Database/Esqueleto/Internal/PersistentImport.hs, /tmp/matrix-worker/1485112890/dist-newstyle/build/x86_64-linux/ghc-7.8.4/esqueleto-2.5.0/build/Database/Esqueleto/Internal/PersistentImport.o )
src/Database/Esqueleto/Internal/PersistentImport.hs:7:1: Warning:
The import item ‘PersistQuery(..)’ suggests that
‘PersistQuery’ has (in-scope) constructors or class methods,
but it has none
[2 of 5] Compiling Database.Esqueleto.Internal.Language ( …
```

Tighten version bound on base

---

esqueleto.cabal
test/Test.hs

persistent use persistent-sqlite >= 2.1
if remove support old persistent-sqlite, we can remove ugly preprocessor.
and, text editor can detect symmetry of blacket.

use persistent-sqlite >= 2.1.3

---

.travis.yml
src/Database/Esqueleto/Internal/Sql.hs
test/Test.hs

The current implementation of `selectSource` does not call the release key, instead waiting for the scope to end with `runResourceT`.
With the SQLite backend, this causes a runtime exception as reported in #29.
This PR introduces a test case for the problem and a solution.

release key with selectSource

---

src/Database/Esqueleto/Internal/Language.hs

From what I can see, the linked issue (#6124) was fixed somewhere along the way, and I don't get any warnings from compiling the testcase from the ticket with ghc-7.10 and later versions.

Replace data with newtype in Value and ValueList.

---

src/Database/Esqueleto.hs
src/Database/Esqueleto/Internal/Language.hs
src/Database/Esqueleto/Internal/Sql.hs
test/Test.hs

Guards against null values with a where_ call. Includes a test as well.
Addresses #61

Add withNonNull helper to project nullable values

---

.travis.yml
esqueleto.cabal
test/Common/Test.hs
test/MySQL/Test.hs
test/PostgreSQL/Test.hs
test/SQLite/Test.hs
test/Test.hs

Removed the CPP pragmas. The tactic for this was to isolate all common tests under `Common/Test.hs` and split the tests for running into different stanzas: postgresql, sqlite, mysql.
At the moment there can be some code duplication, say if one test works the same on both mysql and sqlite but not postgresql they still go in the separate Test.hs files. 
Each of the separate modules defines the backend it's running with, which also ends up looking like duplicate code.
But at least everything looks a lot cleaner and is separated out into digestible parts.

Remove cpp

---

esqueleto.cabal
src/Database/Esqueleto/Internal/Language.hs
src/Database/Esqueleto/Internal/Sql.hs
stack-7.10.yaml
stack-8.0.yaml
stack-8.2.yaml
test/Test.hs

This PR will enable Esqueleto queries to be used by the `persistent-typed-db` library, along with other database backends.
This is a WIP, please don't merge until I've had time to use it in-anger.

Add a class for backend compatibility

---

Makefile

`stack ghci esqueleto:test:test` just fails with the following for me:
```
stack ghci esqueleto:test:test
Error parsing targets: Component CTest "test" does not exist in package esqueleto
Note that to specify options to be passed to GHCi, use the --ghci-options flag
make: *** [test-ghci] Error 1
```
I changed it to invoke `esqueleto:test:sqlite` since that includes all the common tests.
If that's too specific, I can just add some extras for MySQL and Postgres so there are `make-test-ghci-`/`make-test-ghcid-` commands for all the backends.

Adds ghci and ghcid test:sqlite entrypoints to Makefile

---

src/Database/Esqueleto/Internal/Sql.hs
src/Database/Esqueleto/PostgreSQL.hs
test/Common/Test.hs
test/PostgreSQL/Test.hs

This is (some of) the Postgres-specific parts from #75. I have implemented a more generic aggregation function [unsafeSqlAggregateFunction](https://github.com/bitemyapp/esqueleto/compare/master...Philonous:postgresql-additions?expand=1#diff-c901387a600e739ea0b320c45ad0882bR59) that allows setting `ORDER BY` clauses and made `arrayAgg` and `stringAgg` special cases.
This also fixes #68 and a related bug in `arrayAgg`. Note that the types of `arrayAgg` and `stringAgg` had to be changed because of that. (An alternative fix would be to add `COALESCE` clauses to those functions, which would make them more convenient to use and avoid changing the types, but it would break with the mantra that esqueleto translates straightforwardly into SQL)
[Tests are …

Postgresql additions

---

src/Database/Esqueleto/Internal/Sql.hs
src/Database/Esqueleto/PostgreSQL.hs
stack-8.4.yaml

Tests don't build because of https://github.com/lpsmith/postgresql-simple/issues/252

Fix build under GHC 8.4

---

README.md

Opinions seem to differ regarding whether "envoke" is incorrect or just
unusual in modern English (but please educate me if neither is the case):
https://correct-spelling.com/envoke-or-invoke/
https://en.wiktionary.org/wiki/envoke
Thanks for `Esqueleto`!

Fix "wike" and "envoke" typos in README.md

---

.travis.yml

If you inspect the [output](https://travis-ci.org/bitemyapp/esqueleto/jobs/411001100) from a recent travis build you'll see that the `GHCVER=7.10` and `GHCVER=8.00` values are preventing tests from actually running:
```
...
The command "stack test -- esqueleto:postgresql" exited with 1.
$ stack test -- esqueleto:sqlite
Getting project config file from STACK_YAML environment
Could not parse '/home/travis/build/bitemyapp/esqueleto/stack-8.0.yaml':
YAML exception:
Yaml file not found: /home/travis/build/bitemyapp/esqueleto/stack-8.0.yaml
See http://docs.haskellstack.org/en/stable/yaml_configuration/
...
```
I've updated to match the 8.2 and 8.4 versions that are live as of d2fdaaf.

Update `$GHCVER` environment variables in .travis.yml

---

.travis.yml
esqueleto.cabal
package.yaml
stack-8.4.yaml
stack-8.6.yaml
test/Common/Test.hs

With these changes, I was able to run the following successfully on my local machine:
```
$ stack --stack-yaml stack-8.2.yaml test esqueleto\:test\:postgresql
$ stack --stack-yaml stack-8.4.yaml test esqueleto\:test\:postgresql
$ stack --stack-yaml stack-8.6.yaml test esqueleto\:test\:postgresql
```
I presume the other tests work correctly as well, but did not yet take the time to figure out how to set them up on my machine.
I made the same change to `stack-8.4.yaml` as #106 in order to run the test suite successfully for the 8.4 configuration.
Regarding #105, this change (once released) makes esqueleto compatible with the Stackage nightly builds, and therefore ready to be included in the upcoming lts-13.

Update to ghc-8.6 and persistent-2.9

---

.travis.yml
src/Database/Esqueleto/Internal/Language.hs
src/Database/Esqueleto/Internal/Sql.hs
stack-8.4.yaml
test/Common/Test.hs
test/MySQL/Test.hs

This adds the `ForUpdateSkipLocked` to the `LockingKind` type.
Also, travis was broken for MySQL and Postgresql for the following reasons:
- The Posgresql build was failing with the following message:
``` 
• No instance for (Semigroup Query)
arising from the superclasses of an instance declaration
• In the instance declaration for ‘Monoid Query’
|
90 | instance Monoid Query where
|          ^^^^^^^^^^^^
```
Bumping the minor of `postgresql-simple` on `stack.yaml` fixes it.
- The MySQL build is not being able to connect to the database on the master branch. This PR fixes it.
I don't know if this is the best implementation but I am willing to change anything 😄

Add `FOR UPDATE SKIP LOCKED` to possible lock types and fix CI

---

src/Database/Esqueleto.hs
src/Database/Esqueleto/Internal/Language.hs
src/Database/Esqueleto/Internal/Sql.hs
test/Common/Test.hs

Fixes #34 
Please, let me know if there's anything else to be done/fixed regarding this issue 👍

Add between

---

src/Database/Esqueleto.hs
src/Database/Esqueleto/Internal/Language.hs
src/Database/Esqueleto/Internal/Sql.hs
test/Common/Test.hs

Reverts bitemyapp/esqueleto#111
Unfortunately `between` did not work with non-`val` values

Revert "Add between"

---

README.md

LeftOuterJoin example in README contains typo and doesn't type check.
This PR fixes it.

Fix LeftOuterJoin example in README.

---

src/Database/Esqueleto/Internal/Internal.hs

Issue in docs is fix by just using any other variable name that is not Id or id or ID and using Primary to set the new field as key for the table

fix broken example in documentation

---

changelog.md
src/Database/Esqueleto/Internal/Internal.hs
src/Database/Esqueleto/PostgreSQL.hs
test/Common/Test.hs
test/PostgreSQL/Test.hs

Based on #86 I came with insertSelectWithConflict, it is like insertSelect but allows to perform an update if some row conflicts with the new addition on a given constraint. There is no way in postgres (that I could find) of responding to any possible conflict, so a specific one needs to be indicated with a unique.

Insert Select With Conflict for postgres

---

changelog.md
esqueleto.cabal
src/Database/Esqueleto.hs
src/Database/Esqueleto/Internal/ExprParser.hs
src/Database/Esqueleto/Internal/Internal.hs
src/Database/Esqueleto/Internal/Sql.hs
test/Common/Test.hs
test/PostgreSQL/Test.hs

This PR tracks my attempt to fix the on clause ordering issue.
[Previous discussion here](https://github.com/bitemyapp/esqueleto/issues/49#issuecomment-545223824).
TLDR on implementation plan:
- Render the `OnClause (SqlExpr (Value Bool))` into `Text` (lmao)
- Parse the `Text` and find table identifiers - we pretty much have a guarnatee that they'll have the grammar:
```
escape-char [character] escape-char . escape-char [character] escape-char
```
which should make it relatively straightforward to write a parser that will return all the `Ident`s for the `OnClause`.
- Once we have the identifiers associated with the `OnClause`, we can be more selective about finding the appropriate match. The `FromClause` that gets constructed is a binary tree with nodes of `FromClause lhs JoinKind rhs …

Fix the On Clause Ordering issue

---

changelog.md
esqueleto.cabal
src/Database/Esqueleto/Internal/Internal.hs

... without needing to nest tuples. Fixes #162. I've also added a bit more documentation to the `UnsafeSqlFunctionArgument` class, as the fact that you can nest tuples wasn't clear to me until I actually started working on this, and I thought it was mentioning in case anyone else does want to use `unsafeSqlFunction` with more than 10 arguments in the future.

Allow unsafeSqlFunction to take up to 10 args

---

changelog.md
esqueleto.cabal
src/Database/Esqueleto/Internal/Internal.hs

This PR adds several common SQL string functions we noticed were not implemented in the library:
- UPPER
- TRIM
- LTRIM
- RTRIM
- LENGTH
- LEFT
- RIGHT
------------

Add several common SQL string functions

---

changelog.md
esqueleto.cabal
src/Database/Esqueleto.hs
src/Database/Esqueleto/Internal/Language.hs

Unfortunately, when we made #166 earlier today, we forgot to expose the functions we added to make them available in `Database.Esqueleto`. This PR fixes that issue and bumps to v3.3.1.
--------

Exposed new SQL string functions added in v3.3.0 and bumped to v3.3.1

---

changelog.md
esqueleto.cabal
src/Database/Esqueleto/Internal/Internal.hs
test/Common/Test.hs

Update the handling of id fields in the projection operator. Since persistent treats all natural keys as composite keys we can not rely on hasCompositeKey. 
Instead use entityKeyFields to treat surrogate and single field natural keys the same. 
Fixes #176

Update (^.) to fix natural key handling

---

test/Common/Test.hs
test/PostgreSQL/Test.hs

This PR includes a test for date truncation in postgresql. 
Fixes #27 
The observed behavior is somewhat weird on my machine locally:
```
test/PostgreSQL/Test.hs:536:17:
1) PostgreSQL specific tests, date_trunc, works
Falsifiable (after 3 tests and 4 shrinks):
[(0,0,0,0)]
expected: 1999-12-31 07:00:00 UTC
but got: 2000-01-01 00:00:00 UTC
```
The date is generated from this:
```haskell
prop "works" $ \listOfDateParts -> run $ do
let
utcTimes =
map
(\(y, m, d, s) ->
fromInteger s
`addUTCTime`
UTCTime (fromGregorian (2000 + y) m d) 0
)
listOfDateParts
```
So it's weird to me that we get a 07:00:00 at all! We're inserting `UTCTime (fromGregorian 2000 0 0) 0`, which becomes `2000-01-01 00:00:00 UTC`. So why are we getting …

Postgresql Date Truncation

---

changelog.md
esqueleto.cabal
src/Database/Esqueleto/Internal/Internal.hs
test/Common/Test.hs

My coworker Lev was adding this typeclass to our codebase and we hadn't used it before. I added a little more documentation that I think would help clarify things, particularly what the point of the witness function was. More importantly I added a test for this typeclass.

Test and further document ToBaseId

---

changelog.md
esqueleto.cabal
src/Database/Esqueleto/Internal/Internal.hs
src/Database/Esqueleto/PostgreSQL.hs
test/PostgreSQL/Test.hs

[#197] Allow PostgreSQL aggregate functions to take a filter clause

---

src/Database/Esqueleto/Experimental.hs
src/Database/Esqueleto/Internal/Internal.hs
test/MySQL/Test.hs

This is a potential fix for #194. I am not sure that I like the extra SelectQueryP constructor but I don't want to muddy up the api for others and cant really think of a nicer way to convey the information. 
I guess theoretically aliasQuery could use a different data type that is exactly the same but with SelectQuery taking a NeedParens. 
I don't know if that is better or worse, do we want to expose the ability to add parentheses to the user directly?
I am certainly not tied to this, in fact it seems super hacky but so is mysql. I think this is probably better than depending on connRDBMS == "mysql".

Add new SetOperation constructor for parenthesized query

---

README.md
changelog.md
esqueleto.cabal
src/Database/Esqueleto.hs
src/Database/Esqueleto/Experimental.hs
src/Database/Esqueleto/Internal/Internal.hs

---
This PR adds documentation and pointers to the new Experimental module and encourages users to switch to it.

Make the Experimental module more prominent

---

changelog.md
esqueleto.cabal
src/Database/Esqueleto/Experimental.hs

---
This PR deprecates the `ToAliasT` and `ToAliasReferenceT` type families, as both are just the identity on types. This makes it possible for library users to define their own `ToAlias` and `ToAliasReference` instances, which is particularly useful when you're using a custom data type (with a `SqlSelect` instance) in queries.
~~I'm not entirely sure of why we need `ToAliasT` and `ToAliasReferenceT` if in all cases `ToAliasT a ~ a` and `ToAliasReferenceT a ~ a`; maybe they could be removed?~~
Resolves #211

Deprecate ToAliasT and ToAliasReferenceT

---

src/Database/Esqueleto/Experimental.hs

An idea I had while looking through the changes. Not sure if this breaks compatibility with a ghc, but it seems more "minimalistic" and I think it shouldn't be a breaking API change.
@belevy

Use type families instead of empty classes

---

.gitignore
changelog.md
src/Database/Esqueleto/Experimental.hs

Simplify ToFromT moving the overlapping bits out and into their own closed type families with a single purpose. This seems like positive change. 
Make ToMaybeT into an associated type family in the vein of #221 
fix #222

Simplify ToFromT

---

changelog.md
esqueleto.cabal
src/Database/Esqueleto/Experimental.hs

This is a constraint on `on`, but not exported, so you have to go into the source to see what it does. Exporting makes this easier.
(I don't think any `ChangeLog` or version edits are necessary for this)

Also export ValidOnClauseValue

---

changelog.md
esqueleto.cabal
src/Database/Esqueleto/Internal/Internal.hs
src/Database/Esqueleto/PostgreSQL.hs

Got the following error when using `unsafeSqlAggregateFunction`:
```
An exception has occurred: src/Database/Esqueleto/PostgreSQL.hs:94:30-50: Non-exhaustive patterns in lambda
```
This PR fixes the problem.
---

Fix non-exhaustive patterns in 'unsafeSqlAggregateFunction'

---

changelog.md
esqueleto.cabal
src/Database/Esqueleto/Internal/Internal.hs

Improve recommended hlints for catching `x = NULL` SQL

---

changelog.md
esqueleto.cabal
src/Database/Esqueleto/Internal/Internal.hs
test/Common/Test.hs
test/PostgreSQL/Test.hs

Fix group by composite

---

esqueleto.cabal
test/Common/Test.hs
test/Common/Test/Import.hs
test/Common/Test/Models.hs
test/Common/Test/Select.hs
test/MySQL/Test.hs
test/PostgreSQL/Test.hs
test/SQLite/Test.hs
test/Spec.hs

This PR consolidates the test suite and provides a means of further factoring things out from it.
Performing `stack clean && time stack test --fast esqueleto` on `master` and this branch yield a runtime of 2:25 vs 1:47, about 30s of savings. 
Incremental builds are even faster. Factoring out the models into a separate module has a considerable benefit on compile-times. Performing a build (`stack build --test --no-run-tests --fast esquleto`) and then editing `Common.Test` to have an additional test case on `master` results in a rebuild that takes 54s of wall time. On this branch, the same change takes 12s to rebuild.

Consolidate Tests

---

.gitignore
Makefile
esqueleto.cabal
test/Common/Test.hs
test/Common/Test/Import.hs
test/Common/Test/Select.hs
test/MySQL/Test.hs
test/PostgreSQL/MigrateJSON.hs
test/PostgreSQL/Test.hs
test/SQLite/Test.hs

This PR inverts control in the test suite. Instead of having each test suite provide a `run` function which runs the database action, the test suite expects a `ConnectionPool` to be made available to it. Then the various backends use `beforeAll :: IO ConnectionPool -> SpecWith ConnectionPool -> Spec` to make it happen.
A further advantage is that we'll be able to use `beforeWith :: (ConnectionPool -> IO ConnectionPool) -> SpecWith ConnectionPool -> SpecWith ConnectionPool` to implement things like, y'know, inserting test/setup data into the database, and `afterWith` to clean it up.

Pass ConnectionPool to tests

---

changelog.md
esqueleto.cabal
src/Database/Esqueleto.hs
src/Database/Esqueleto/Experimental.hs
src/Database/Esqueleto/Internal/Internal.hs
src/Database/Esqueleto/Legacy.hs
test/Common/Test.hs

Add `selectOne`

---

changelog.md
esqueleto.cabal
src/Database/Esqueleto/Internal/Internal.hs
test/Common/Test.hs

Postgres treats `x in ()` and `x not in ()` as syntax errors. Instead translate:
```plaintext
x in ()      ⇒  FALSE
x not in ()  ⇒  TRUE
```
Older versions of esqueleto did both of these, but apparently the latter got lost in the most recent version. See issue #272.

Avoid generating an empty list as the left operand to NOT IN

---

changelog.md
esqueleto.cabal
src/Database/Esqueleto/Internal/Internal.hs
test/PostgreSQL/Test.hs

Should solve https://github.com/bitemyapp/esqueleto/issues/277.
Code assembling `DISTINCT ON` clause was stripping important part of important nested expressions. It worked well without nested expressions but with them it just cuts by spaces parts with arguments. So for example with `COALESCE(val, ?) ASC` it splits assembled expression into `["COALESCE(val,", "?)", "ASC"]` which causes bad sql for some cases.
I am not sure it is a good solution because I actually don't know is it possible to have other expressions here or not? Please, let me know if you see any other possible issues with that fix. :)
A related test-case is added.

Fix distinctOnOrderBy with nested expression

---

changelog.md
esqueleto.cabal
src/Database/Esqueleto/PostgreSQL.hs
test/PostgreSQL/Test.hs

At my company we really wanted to use `VALUES` Postgres expression to use it inside of `JOIN`
between large db data-set with some smaller user-input data-set without loading of data into app-memory.
`VALUES` allows us to do that and even gives performance benefit to our app.
I think it is a relevant issue https://github.com/bitemyapp/esqueleto/issues/231 :)
This PR tries to bring an ability to use like:
*SQL* : `SELECT * FROM (VALUES (a1), (a2) ...) as "vs"("v1")`
*Haskell*: `select $ from $ values [val 1, val 2, val 3]`
It also works for more than one columns as well (a bit doubting about aliases/refs assembling but works good so far). :)
I implemented it as part of `From` and thanks to latest refactoring from
GADTs to type-classes it was not so difficult :)
Few appropriate …

Add support of PostgreSQL-specific `VALUES(..)` expression

---

changelog.md
esqueleto.cabal
src/Database/Esqueleto/Experimental/From/Join.hs
test/Common/Test.hs

The (:&) operator has an instance for `SqlSelect`, but none
for `ToAlias` and `ToAliasReference`. Adding those for parity.
I'm not sure if the should be a patch or major version bump. Adding new instances can break existing code, but they are such small instances ... I guessed and bumped the patch number.
I was unable to get the testing environment working locally, so I was going to rely on CI to execute my tests.  🤞 
Related to #290.

Add missing instances to (:&)

---

README.md

It's been a long time since I remembered MySQL user naming convention stuff, but, just empirically I get the following error following the README instructions:
```
mysql -u root
```
```
mysql> GRANT ALL ON esqutest.* TO 'travis';
ERROR 1410 (42000): You are not allowed to create a user with GRANT
mysql> GRANT ALL ON esqutest.* TO 'travis'@'localhost';
Query OK, 0 rows affected (0.00 sec)
```
MySQL version:
```
~/D/C/H/esqueleto> mysql --version                                                                                                                                                                                                                                                                                                                                  12:38:37
mysql  Ver 8.0.22 …
```

Add @localhost to last MySQL command

---

changelog.md
esqueleto.cabal
src/Database/Esqueleto/Internal/Internal.hs

the implementation seem shared,
it took me a couple of minutes to figure this out,
it seems wise to add a seperate header showing how,
it ought to work for the new API.

Add docs for experimental delete

---

changelog.md
esqueleto.cabal
src/Database/Esqueleto/Internal/Internal.hs
src/Database/Esqueleto/PostgreSQL.hs

This PR removes the `SqlReadT` and `SqlWriteT` uses that would trigger compilation errors for folks on GHC 9.

Remove alias that has problems with Simplified Subsumption

---

src/Database/Esqueleto/Experimental/From/CommonTableExpression.hs

This note was *probably* targeted at Postgres always materializing CTEs, but is only conditionally true now.

Add note below the CTE WARNING about the notable postgres change

---

changelog.md
esqueleto.cabal
src/Database/Esqueleto/Record.hs
test/Common/Record.hs

Support nested records in `deriveEsqueletoRecord`

---

.github/workflows/haskell.yml
stack-8.6.yaml

[GHC 8.6.5 is broken with module re-exports](https://github.com/haskell/haddock/issues/979#issuecomment-485341270). We can either re-export everything, or just skip building Haddock. I'd rather skip building Haddocks for an old GHC than make the code experience worse, or more fragile.

Skip Haddock for GHC 8.6.5

---

changelog.md
esqueleto.cabal
src/Database/Esqueleto/Record.hs
test/Common/Record.hs

These instances are required for some Esqueleto functions, such as using records in Common Table Expressions with `with`.
They are simply defined by lifting the record SQL constructor over the appropriate monad.

Add `ToAlias`, `ToAliasReference` to `deriveEsqueletoRecord`

---

changelog.md
esqueleto.cabal
src/Database/Esqueleto/Record.hs
test/Common/Record.hs

This adds an Aeson-inspired ability to configure how `deriveEsqueletoRecord` generates the SQL record type, in particular which names it generates for the record type itself and its fields.
This is because `DuplicateRecordFields` is a painful extension to use, and avoiding it through module structuring is also painful. A nicer solution for avoiding duplicate record fields is to simply not generate them, and allow the user to specify how record fields should be generated so they don't overlap.

Add customisation of auto-gen'ed SQL record names

---

changelog.md
esqueleto.cabal
src/Database/Esqueleto/Experimental/From/SqlSetOperation.hs
src/Database/Esqueleto/Experimental/ToAlias.hs
test/PostgreSQL/Test.hs

#334  broke the behavior of nested subqueries
`from $ from $ from table` would not correctly re-alias the values.
This PR reverts that fix and substitutes it with a different one that addresses union(set operations) directly by changing how it reuses variable names. 
Lesson Learned: Do not try to reuse variable names unless you want pain

Revert change to ToAlias and refix union bug

---

changelog.md
src/Database/Esqueleto.hs
src/Database/Esqueleto/Experimental.hs
src/Database/Esqueleto/Experimental/From/Join.hs
src/Database/Esqueleto/Internal/Internal.hs
src/Database/Esqueleto/Legacy.hs
src/Database/Esqueleto/PostgreSQL.hs
test/Common/Test.hs
test/PostgreSQL/Test.hs

**Context:**
Support `FOR UPDATE Of tablename` and `FOR SHARE OF tablename` syntax for Postgresql:
This allows a the `FOR UPDATE SKIP LOCKED`  behaviour when you have a `LEFT OUTER JOIN` with a nullable side.  Currently you will get the error:
```
FOR UPDATE cannot be applied to the nullable side of an outer join
```
The workaround currently using esqueleto is to do seperate queries and then join them manually if you want to select rows for an update while skipping locked rows (or to just do a raw query). I ran into this situation at work.
See: https://www.postgresql.org/docs/current/sql-select.html
namely:
```
FOR { UPDATE | NO KEY UPDATE | SHARE | KEY SHARE } [ OF table_name [, ...] ] [ NOWAIT | SKIP LOCKED ] [...] ]
```
also documented in MySQL: …

Support more locking kind

---

changelog.md
esqueleto.cabal
src/Database/Esqueleto/Experimental.hs
src/Database/Esqueleto/Experimental/From/Join.hs

This fixes #307, which has recently resurfaced on [a Stack Overflow question](https://stackoverflow.com/q/76234412/2751851). I believe the examples adjusted here were the only ones still missing `just`.

Add missing just to left join examples in the Haddocks

---

changelog.md
esqueleto.cabal
src/Database/Esqueleto/Experimental.hs
src/Database/Esqueleto/Internal/Internal.hs

This PR adds `isNothing_`, `groupBy_`, and `updateE` as "non-conflicting" variants of the other esqueleto  functions. This helps avoid name conflicts and makes it easier to import `esqueleto` with other libraries.

Name conflict dodges

---

changelog.md
esqueleto.cabal
src/Database/Esqueleto/Experimental/ToAlias.hs
src/Database/Esqueleto/Experimental/ToAliasReference.hs
src/Database/Esqueleto/Internal/Internal.hs

This adds a `ToAlias` and `ToAliasReference` instance for every tuple size from 9 to 16. These tuple sizes are supported elsewhere, but those typeclasses only had instances for tuples up to size 8.
This also adds `from*` functions for tuples of size 9-16, which didn't exist before.
Do I need to add Haddocks and `@since` declarations for these functions, given that they're in the `Internal` module?

Add `ToAlias`, `ToAliasReference` for <=16-tuples

---

changelog.md
esqueleto.cabal
src/Database/Esqueleto/Internal/Internal.hs
src/Database/Esqueleto/PostgreSQL.hs
test/PostgreSQL/Test.hs

Fix Postgres syntax for NOWAIT

---

changelog.md
esqueleto.cabal
src/Database/Esqueleto/Record.hs
test/Common/Record.hs

Generate `ToMaybe` in `deriveEsqueletoRecord`

---

changelog.md
esqueleto.cabal
src/Database/Esqueleto/Record.hs
test/Common/Record.hs

Required ToMaybe, ToAlias, ToAliasReference instances for SqlMaybes
Also, required implementation changes to the sqlSelectProcessRow for SqlMaybes
- [N/A] Documented new APIs with [Haddock markup](https://www.haskell.org/haddock/doc/html/index.html).
- [N/A] Added [`@since` declarations](http://haskell-haddock.readthedocs.io/en/latest/markup.html#since) to the Haddock.

Add support for nested Maybe records

---

changelog.md
esqueleto.cabal
src/Database/Esqueleto/Internal/Internal.hs
src/Database/Esqueleto/PostgreSQL.hs
test/PostgreSQL/Test.hs

See [postgres docs](https://www.postgresql.org/docs/current/explicit-locking.html#LOCKING-ROWS). `FOR NO KEY UPDATE` and `FOR KEY SHARE` were not previously included in Esqueleto but can be useful.

add all postgres row-level locking options

---

changelog.md
esqueleto.cabal
src/Database/Esqueleto/Record.hs

No need to be this restrictive in deriveEsqueletoRecord For example, AppT ListT _ and AppT (ConT _) _ are both fine but would throw an error here before this change.

Do not error on any AppT in sqlMaybeSelectProcessRowDec

---

src/Database/Esqueleto/Internal/Internal.hs
test/Common/Test.hs

This PR fixes #359 by always wrapping arguments to `not_` in parentheses when building SQL queries. Some tests combining `not_` with `&&.` and `||.` have also been added to `Common.Test`.
This is technically a breaking change: `not_ (x &&. y)` is no longer equivalent to `(not_ x) &&. y`, for example, although the equivalence is probably unintended.
---
- `stylish-haskell` fails to parse the `DEPRECATED` pragma for `sub_select` in `Database.Esqueleto.Internal.Internal`.

Fix semantics of `not_` applied over `&&.` and `||.`

---

changelog.md
esqueleto.cabal
src/Database/Esqueleto/Record.hs

This eliminates some CPP by switching to using TH quotes.

Use TH quotes more to eliminate some CPP

---

changelog.md
src/Database/Esqueleto/Internal/Internal.hs

Supercedes #346 and fixes #408

Docs on boolean operators

---

src/Database/Esqueleto/PostgreSQL.hs
test/PostgreSQL/Test.hs

Add NULLS FIRST / NULLS LAST qualifiers for ordering

---

changelog.md
src/Database/Esqueleto/Internal/Internal.hs

Add Functor and Bifunctor instance for pairs

---

changelog.md
esqueleto.cabal
src/Database/Esqueleto/Experimental/ToAliasReference.hs
src/Database/Esqueleto/Internal/Internal.hs

Remove `Coercible` abiilty for `SqlExpr`.

---

changelog.md
src/Database/Esqueleto.hs
src/Database/Esqueleto/Experimental.hs
src/Database/Esqueleto/Experimental/From.hs
src/Database/Esqueleto/Experimental/From/SqlSetOperation.hs
src/Database/Esqueleto/Experimental/ToAlias.hs
src/Database/Esqueleto/Experimental/ToAliasReference.hs
src/Database/Esqueleto/Internal/Internal.hs
src/Database/Esqueleto/Legacy.hs
src/Database/Esqueleto/PostgreSQL.hs
test/Common/Test.hs
test/Common/Test/Models.hs
test/PostgreSQL/Test.hs
test/SQLite/Test.hs

This PR deprecates `ilike` and removes all terms deprecated prior to 3.5.
Fixes #364 
Fixes #288 

Deprecation Cycles for 3.6

---

changelog.md
src/Database/Esqueleto.hs
src/Database/Esqueleto/Experimental.hs
src/Database/Esqueleto/Internal/Internal.hs
src/Database/Esqueleto/Legacy.hs
src/Database/Esqueleto/MySQL.hs
src/Database/Esqueleto/PostgreSQL.hs

This PR deprecates the `LockingKind` constructors as they will be removed from non-`Internal` module in a future release. Smart constructors are provided as alternatives.
Fixes #319 

Deprecate LockingKind constructors

---

.github/workflows/haskell.yml
changelog.md
src/Database/Esqueleto.hs
src/Database/Esqueleto/Experimental/ToMaybe.hs
src/Database/Esqueleto/Internal/Internal.hs
src/Database/Esqueleto/Legacy.hs
test/Common/Test.hs

This may make type inference *really* bad, so I want to do a lot more experimentation with it before committing to this. The convenience would be very nice but not if the error messages get really bad.
Closes #407 
Might as well fold a few more items into this PR. Other functions which produce `SqlExpr (Value (Maybe a))` should probably do `Nullable` here also.

`HasField` for `SqlExpr (Maybe (Entity a))` joins `Maybe`

---

.github/workflows/haskell.yml
Makefile
changelog.md
esqueleto.cabal
examples/Main.hs
src/Database/Esqueleto.hs
src/Database/Esqueleto/Experimental.hs
src/Database/Esqueleto/Experimental/From.hs
src/Database/Esqueleto/Experimental/From/SqlSetOperation.hs
src/Database/Esqueleto/Experimental/ToAlias.hs
src/Database/Esqueleto/Experimental/ToAliasReference.hs
src/Database/Esqueleto/Experimental/ToMaybe.hs
src/Database/Esqueleto/Internal/Internal.hs
src/Database/Esqueleto/Legacy.hs
src/Database/Esqueleto/MySQL.hs
src/Database/Esqueleto/PostgreSQL.hs
stack-9.0.yaml
test/Common/Test.hs
test/Common/Test/Models.hs
test/PostgreSQL/Test.hs
test/SQLite/Test.hs
test/Spec.hs

This PR is the rollup of changes for version 3.6.0.0

Version 3.6.0.0
